### ISSUE TITLE
Waiting for Approval widget should be yellow if it has any approvals

### ISSUE THREAD

**Issue by darafsheh** [service-bot/servicebot#133]
If there are approvals, the approval widget should be a yellow color. Otherwise, it could be the current color.

**Comment by lsydev** [comment]
Do you mean the admin's dashboard widgets? if Requested service is > 0 then make it yellow?

**Comment by darafsheh** [comment]
No I mean the users My Services page.

**Comment by darafsheh** [comment]
This has been completed redesigned.
