### ISSUE TITLE
Setting up a new trial account fails

### ISSUE THREAD

**Issue by heliodor** [service-bot/servicebot#167]
- Go to front page (servicebot.io)
- Click the "Get Started" button
- Fill in email, password, business name
- Follow instructions on the next page
- Click the "Submit" button
- Page reloads with no changes or error messages

Inspecting the http calls, I see a `POST` to `/setup` which returns the error message`All fields are required`. This error message appears in this code: [https://github.com/service-bot/servicebot/blob/383eae52b845ed200cc0dc0186dd876fa44b70da/bin/www#L233](https://github.com/service-bot/servicebot/blob/383eae52b845ed200cc0dc0186dd876fa44b70da/bin/www#L233)

No error message is shown to the user on the web page though.

Inspecting the `POST` request, I see only the two Stripe keys as the body of the message. According to the code, the following should be included in the body: `admin_user`, `admin_password`, `company_name`, and `company_email`.

Lastly, because the email and business names are required to be unique in the database, my choices are now not available anymore, and I have no way to continue the process of setting up with those ids.

**Comment by darafsheh** [comment]
Hi @heliodor, I see that you created two instances. I would like to help you with this, so lets take one of the instances you create and set it up. It could be easier to go through a screen share with you. I have just tested this and seems to be working fine from my end. I will email you and we can go through it together on a screen share maybe.

**Comment by darafsheh** [comment]
Basically, try to type in your password (avoid line breaks in there) when you setup for a new ServiceBot instance. It looks like the password field is empty, which makes me believe that a special character or linespace might have cause the password not to save properly. Just type in a simple password during the signup process and let me know if that works.

**Comment by darafsheh** [comment]
Marking this closed. Let us know if you need any more help.
