### ISSUE TITLE
Delete request button in UI not sending API call

### ISSUE THREAD

**Issue by kmidkiff** [service-bot/servicebot#176]
To recreate, request service as admin for a user. Then go to manage catalog and click delete request. Request delete popup will shop up but button does nothing

**Comment by darafsheh** [comment]
2 hr

**Comment by darafsheh** [comment]
Turns out this API doesn't actually exist. I will be creating this API. @kmidkiff Can you let me know the swagger steps for the new route?

**Comment by darafsheh** [comment]
Decision on this story: I currently am not sure what bugs we will introduce by allowing services to be fully removed. To complete this story, I will allow admins to cancel any service that is currently not on a cancelled status. I will also attempt to separate the cancelled services on the UI.

**Comment by darafsheh** [comment]
Commit was made. Forgot the # on the issue. Closed.
