### ISSUE TITLE
The page after a successful service template creation needs style

### ISSUE THREAD

**Issue by darafsheh** [service-bot/servicebot#187]
After creating a new service template the page is all blank with a simple text saying "template created".. This page needs an icon and style

**Comment by darafsheh** [comment]
Or just redirect the user to the Manage Catalog page after with a success message.

**Comment by lsydev** [comment]
should we just push the user to the template request form page? so they can see what they made immediately?

**Comment by darafsheh** [comment]
We need to push the user to the manage catalog page so they can see the catalog list.
