### ISSUE TITLE
Template icon upload crashes

### ISSUE THREAD

**Issue by lsydev** [service-bot/servicebot#196]
![image](https://user-images.githubusercontent.com/19615360/31157702-bedb9a68-a88a-11e7-9b74-d27c12c204b1.png)
happens after selected icon, click on save and server crashes.
it is editing existing template, image is already uploaded, and just upload the icon and save it.

**Comment by lsydev** [comment]
also happens when clicking on remove icon button

**Comment by kmidkiff** [comment]
I believe this is because of starting a server from fresh. The DB is cleared, but the uploads directory is not cleared. So a new template is created with the same ID as an old one that had an image, so some collision is happening. Should be **fixed by clearing uploads directory**
