### ISSUE TITLE
User profile has no input validation

### ISSUE THREAD

**Issue by bsears90** [service-bot/servicebot#220]

**Comment by lsydev** [comment]
I don't know what form system this is on, but do we want to just add validation to it? or change it to redux form? It's a good time for me to learn how to make a redux form. But @kmidkiff can u tell me how long it would take u if u were to do it?

**Comment by darafsheh** [comment]
I think it makes more sense for you to learn redux form and use this as the task to learn it. Validations are much cleaner with redux form.

**Comment by lsydev** [comment]
I think so too, i just want to know if @kmidkiff could guesstimate it, so we have an idea about how long it takes if we were to do that vs just adding validation to it.

**Comment by kmidkiff** [comment]
without styling. and figuring out the 2 fields that go into one for password validation. 2 hrs
