### ISSUE TITLE
Issue moving from $0 Subscription

### ISSUE THREAD

**Issue by bsears90** [service-bot/servicebot#239]
A $0 subscription can be upgraded to have an actual subscription 

This should trigger a step for the user to approve. 

A user without funds could be upgraded to a subscription without this functionality

I'd also look into removing the ability to have a $0 subscription completely as it should be treated like a custom service

**Comment by lsydev** [comment]
[15min - 2hr]

**Comment by kmidkiff** [comment]
front and backend change that shoullllld be minor if we want to get rid of $0 subscription...

**Comment by bsears90** [comment]
The solution should be to make the input on the template form blank instead of $0, and validate to be greater than $0.

We can also handle some server side stuff if we want
