### ISSUE TITLE
Create style for error

### ISSUE THREAD

**Issue by kmidkiff** [service-bot/servicebot#242]
Here they are in UI
<img width="528" alt="screen shot 2017-10-12 at 11 09 27 am" src="https://user-images.githubusercontent.com/6853957/31503531-eae9b64e-af3d-11e7-9f3d-6870c2656860.png">
Here it is in the new template form. They will also be in the others
<img width="271" alt="screen shot 2017-10-12 at 11 09 54 am" src="https://user-images.githubusercontent.com/6853957/31503542-f0eec480-af3d-11e7-92ba-95f39fab74c7.png">
Maybe we should just put it at the bottom where the submit button is so we don't have to worry about the scrolling?

**Comment by lsydev** [comment]
umm .. why does doesn't go under the field?

**Comment by lsydev** [comment]
1 hr
