### ISSUE TITLE
Feature Settings Edit button appears in the middle of the screen

### ISSUE THREAD

**Issue by kmidkiff** [service-bot/servicebot#256]
<img width="1250" alt="screen shot 2017-10-19 at 3 30 04 pm" src="https://user-images.githubusercontent.com/6853957/31792692-7f7dc3a0-b4e2-11e7-8b9a-76c22ce122e0.png">

**Comment by darafsheh** [comment]
Yea not sure if this was a change made by design or not. I will look into it as well.

**Comment by lsydev** [comment]
it's not by design .. it's just the result of not having enough time to perfect the layout structure when separating from other pages.
