### ISSUE TITLE
subscription id displayed on service instance page. remove it

### ISSUE THREAD

**Issue by kmidkiff** [service-bot/servicebot#261]
<img width="437" alt="screen shot 2017-10-20 at 2 52 15 pm" src="https://user-images.githubusercontent.com/6853957/31837316-62a1d158-b5a6-11e7-95d4-8a641fcec470.png">

**Comment by lsydev** [comment]
i don' t see this on instance page

**Comment by kmidkiff** [comment]
It's there, towards the top of the page, near the header

**Comment by kmidkiff** [comment]
<img width="855" alt="screen shot 2017-10-22 at 3 54 28 pm" src="https://user-images.githubusercontent.com/6853957/31865717-5140dd5e-b741-11e7-982a-017120261144.png">
