### ISSUE TITLE
ERROR in ./node_modules/pluginbot-react/src/provider.js     Module parse failed: Unexpected token (17:16)

### ISSUE THREAD

**Issue by Ezehuche** [service-bot/servicebot#293]
I getting this issue when I run "npm run-script build".

ERROR in ./node_modules/pluginbot-react/src/provider.js
    Module parse failed: Unexpected token (17:16)
    You may need an appropriate loader to handle this file type.
    |
    |     render(){
    |         return (<Provider store={this.props.pluginbot.store}>
    |         {this.props.children}
    |     </Provider>)
     @ ./views/router.jsx 51:16-55
     @ ./views/index.jsx
     @ multi react-hot-loader/patch ./views/index.jsx

    ERROR in ./node_modules/pluginbot-react/src/consume.js
    Module parse failed: Unexpected token (23:24)
    You may need an appropriate loader to handle this file type.
    |         class ServiceConsumerWrapper extends React.Component{
    |             render(){
    |                 return (<Component {...this.props}/>)
    |             }
    |         }
     @ ./views/router.jsx 59:15-53
     @ ./views/index.jsx
     @ multi react-hot-loader/patch ./views/index.jsx

    ERROR in ./node_modules/pluginbot/src/pluginbot-base.js
    Module parse failed: Unexpected token (99:16)
    You may need an appropriate loader to handle this file type.
    |
    |             let initialReducer = combineReducers({
    |                 ...reducers,
    |                 pluginbot: pluginbotReducer
    |             });
     @ ./node_modules/pluginbot-react/pluginbot-react.js 2:20-59
     @ ./views/store.js
     @ ./views/router.jsx
     @ ./views/index.jsx
     @ multi react-hot-loader/patch ./views/index.jsx

Please, can you help out?. Thanks

**Comment by bsears90** [comment]
This looks like an issue with babel not able to read the [spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax). 

What version of Servicebot are you running?

**Comment by Ezehuche** [comment]
0.8.4

**Comment by lucwj** [comment]
I got the same issue. May the problem in babel loader in `pluginbot-react` & `pluginbot`

**Comment by bsears90** [comment]
Can you try running the build again on [v0.9.1](https://github.com/service-bot/servicebot/tree/v0.9.1)? 

I think this is a problem which only affects Windows which is why I haven't been able to replicate it on my machine.
