### ISSUE TITLE
Users are able to subscribe to the same subscription multiple times

### ISSUE THREAD

**Issue by danilorod** [service-bot/servicebot#297]
When logged in as a user I was able to subscribe to the same product(subscription) multiple times. I verified the subscriptions in Stripe and they were created there as well. Is this the intended behavior or am I missing  some configuration?

**Comment by darafsheh** [comment]
@danilorod That is an intended behavior. Each service can be ordered by the same person multiple times, just like you would purchase a product from an eCommerce store.

Do you have a specific use-case that needs the user to only purchase the service once?

**Comment by danilorod** [comment]
@darafsheh The use-case would be: 

I'm creating a subscription service with tiers. Users should be able to subscribe to only one of them. 

For example:

My SaaS 

- Starter Tier $15

- Pro Tier $30

The user would be charged monthly for the subscribed tier. Also, the user should not subscribe to multiple tiers of the same service and only once for any given tier. The tiers should be configured for the same product if its type is subscription.

This is a common functionality in any subscription service. I've used WooCommerce Subscriptions and it has this feature.

**Comment by darafsheh** [comment]
@danilorod you should be using the custom fields pricing. At the bottom of the service creation page, you can add custom fields and attach pricing to each. This feature is made to allow tier-based pricing. 

However, once the user purchased your service, they are allowed to re-purchase the same service again. Limiting number of purchases feature doesn’t exist yet. I add it to our backlog to be added to the roadmap.

**Comment by danilorod** [comment]
@darafsheh Excellent!
