### ISSUE TITLE
Email validation incorrectly refuses email of form user+tag@example.com

### ISSUE THREAD

**Issue by sjlongland** [service-bot/servicebot#300]
If the user enters an email address of the form `user+tag@example.com`; ServiceBot incorrectly declares "Invalid email format".

RFC882 explicitly permits this, and it is a very useful way to filter and sort mail.  Many mail servers support this, including Postfix SMTP; as well as email providers such as Gmail.

https://tools.ietf.org/html/rfc822#section-3.3

**Comment by darafsheh** [comment]
@sjlongland We have fixed this issue in the master branch. Let us know if you need any further help.
