### ISSUE TITLE
[enhancement] Currency when "adding charge" is different from System settings

### ISSUE THREAD

**Issue by guillaumegarcia13** [service-bot/servicebot#350]
**Add charge**

I set up my offerings to be in € (EUR).
Yet, when I edit the service instance and click on "Add Charge", the price is set in $ (USD)
![image](https://user-images.githubusercontent.com/2786038/40146982-f8019d40-5967-11e8-8534-f6f14907e9c7.png)

**Edit Payment Plan**

Similarly, when editing payment plan, USD currency ($) is shown in the popup even though the value is the right one.
![image](https://user-images.githubusercontent.com/2786038/40147094-7bfc62f6-5968-11e8-9400-2cf86b84bddc.png)

Lastly, the $ symbol from font-awesome might be misleading (not sure whether font-awesome has all icons for servicebot-supported currencies though...)

_PS: popups have been resized using Chrome DevTools for the purpose of seeing data in the background_

**Comment by kmidkiff** [comment]
Hi Guillaume,
Thanks for creating the issue . :) . My last commit should resolve this
