### ISSUE TITLE
How to retrieve current (paid) subscriptions of one user via API

### ISSUE THREAD

**Issue by utrenkner** [service-bot/servicebot#375]
I just started looking into servicebot. I looked through the (API)-documentation but could not immediately see which API call would allow us to retrieve information about the current subscriptions of a user. This is something we would need to integrate servicebot with our app.

Thanks for a short hint to the right place in the documentation (or any other info).

**Comment by darafsheh** [comment]
The easiest way to get the subscription (service_instance) of a user is:

GET http://<servicebot_URL>/api/v1/service-instances/search?key=user_id&value={user_id}

**Comment by utrenkner** [comment]
Thanks for the quick help!
