### ISSUE TITLE
Drop-down menu for Currency is empty

### ISSUE THREAD

**Issue by greppp** [service-bot/servicebot#385]
We cannot set a currency in the settings.
![screenshot_2018-12-07_12-32-12](https://user-images.githubusercontent.com/15223909/49663659-5745fc00-fa1d-11e8-857c-3f3762f7b6ff.png)
. It looks like by default it is USD as all our clients were charged in USD instead of CAD. What could cause the drop down menu to be empty? Also, how could we force it to be CAD asap, as we need to reimburse them and re-charge them in the correct currency.

Thanks

**Comment by matzrm** [comment]
Is there a solution for this?

**Comment by dudeisbrendan03** [comment]
Did you sort this out?

**Comment by greppp** [comment]
It's been a while, i was using version 0.9.11 but apparently upgrading to the newest version would have fixed this. But in the newest version a lot of functionalities that servicebot used to offer disappeared, so we switched to another open source solution (invoice ninja).

Here is what someone answered me for another empty menu problem : https://github.com/service-bot/servicebot/issues/386

**Comment by greppp** [comment]
You might be able to bypass it by editing some settings files but then you might run into other problems that this version still have, like when you try to reimburse people for example  https://github.com/service-bot/servicebot/issues/386

**Comment by dudeisbrendan03** [comment]
You should close this as it's been resolved in a newer version.
