### ISSUE TITLE
Manage Categories Page

### ISSUE THREAD

**Issue by drjagan** [service-bot/servicebot#47]
Hi,
I may be wrong, but I do not see categories management in the system. 
I would like to edit category name and description.
Please let me know how to do that.

If this feature is not present, can you please add it to the feature request queue?

Thank you

**Comment by kmidkiff** [comment]
Hello,
You can currently add categories from the service template creation page. Where you can set the category of the item, there is a button to add. We will work on a separate page to manage categories though

**Comment by kmidkiff** [comment]
Hi drjagan,
I've added this page to the system. /manage-categories is now up

**Comment by drjagan** [comment]
Fantastic! Thank you @kmidkiff!
