### ISSUE TITLE
Add default_user_role system option

### ISSUE THREAD

**Issue by darafsheh** [service-bot/servicebot#67]
Add a new system option called "default_user_role", make all the user creation functions to pull the value of that variable and create the user with that role.

**Comment by bsears90** [comment]
should we allow system option to be able to be inputted by admin? Pull dropdown of all roles and let the user decide?

**Comment by darafsheh** [comment]
@kmidkiff This issue is now reassigned to you. Here is what we need:

- A system option for default_user_role - This option will allow admins to set what is the user role that will be getting created. We are currently hard coding it.
- The System option must be set to private so it does not show on the system settings. 
- We need a new route to basically take in a role name and will populate this option with the ID of that role
- Lastly, we need to set all the currently statically set user roles to pull this system option value.
- We do have to create the UI piece for this to pull in all user roles and populate them into a drop down in the managed user page or the system settings page. Ask @lsydev where would be the best location.
